### ISSUE TITLE
Why the extra `typename` keywords?

### ISSUE THREAD

**Issue by Qix-** [LeviTaule/exma2D#1]
Just a question; what do the [extra `typename`](https://github.com/LeviTaule/exma2D/blob/master/include/exma2D/vector2D.hpp#L264) template parameters do?

``` c++
template <typename T, typename N, typename, typename, typename>
constexpr T operator*(const T vector, const N factor);
```

**Comment by LeviTaule** [comment]
They do a kind of [compile-time checking](https://github.com/LeviTaule/exma2D/blob/master/include/exma2D/impl/vector2D.cpp#L61-L65).
Using [SFINAE](http://en.cppreference.com/w/cpp/language/sfinae) these template parameters ensure  the function is generated only for certain kind of types, which are valid for the purposes of the function.

For instance, the previously linked parameters ensure certain properties of the types of the passed arguments (without explicitly specifying which types)

``` cpp
  typename = 
std::enable_if_t<std::is_arithmetic<decltype(std::declval<T>().x)>{}>,
```

ensures `T` has an `x` member and that this member is arithemtic

``` cpp
  typename = 
std::enable_if_t<std::is_arithmetic<decltype(std::declval<T>().y)>{}>,
```

ensures `T` has an `y` member and that this member is arithemtic

``` cpp
typename = typename std::enable_if_t<std::is_arithmetic<N>{}>
```

ensures `N` is arithmetic

**Comment by Qix-** [comment]
I see, I didn't look far enough into it. Checked out the definitions and saw them there.

Thanks!
